#docker-compose up -d

version: '3.8'

networks:
  net:
    external: true
    name: global_net

services:
    web:
        image: nginx:alpine
        container_name: nginx_test28
        volumes:
            - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./ssl:/etc/ssl"
            - "../laravel:/app"
            - "./nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "8080:80"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
        networks:
            - net
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        container_name: php_test28
        restart: always
        volumes:
            - "./php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "../laravel:/app"
        networks:
            - net

    mysqldb:
        platform: linux/x86_64
        image: mysql:${MYSQL_VERSION}
        container_name: mysql_test28
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - "./mysql_data/db/mysql:/var/lib/mysql"
        networks:
            - net

    composer:
        image: "composer"
        container_name: composer_test28
        volumes:
            - "../laravel:/app"
        command: install --ignore-platform-reqs
